name: Test coverage

on:
  workflow_dispatch:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::covr, any::xml2
        needs: coverage
    - name: Test coverage
      shell: Rscript {0}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: covr::codecov(quiet=FALSE)
